[postgres]
host = "localhost"
port = 5432
dbname = "form_generator"
user = "postgres"
password = "sABBA@2004"

SENDER_USER="ayakhan5000@gmail.com"
SENDER_PASSWORD="hpcg hjou qdgr alsp"
SMTP_SERVER="smtp.gmail.com"
SMTP_PORT=587
